export const ERROR_CODES = {
      PAGE_NOT_FOUND: 'ER022',
      SYSTEM_ERROR: 'ER023',
      DEPARTMENT_FETCH_FAILED: 'ER024',
      EMPLOYEE_FETCH_FAILED: 'ER025',
      CERTIFICATION_FETCH_FAILED: 'ER026',
};